install: 
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

services: 
  - postgresql  

script:
   - bundle exec rails db:create 
  - bundle exec rails db:migrate
  - bundle exec rails db:environment:set RAILS_ENV=test 
  - bundle exec rails webpacker:compile
  - bundle exec rspec
